### PR TITLE
Add build support using CMake + vcpkg

### PR DESCRIPTION
**Pull request by reitowo**

### CODE REVIEW

**Comment by jrobeson** [comment]
I explicitly chose not to use cmake here.

**Comment by cnSchwarzer** [comment]
> I explicitly chose not to use cmake on this project.

LOL, but why? 
Anyway I just want to make life easier for vcpkg guys.

**Comment by jrobeson** [comment]
there should be an easier way to use qt from vcpkg without changing build systems.

**Comment by cnSchwarzer** [comment]
I'm not requiring to change the build system, but adding another build system (in parallel).
vcpkg is strongly tied with CMake so there probably not.

**Pull request closed without merging**
